spring:
  profiles:  dev
  application:
    name:  springcloud-config-server-dev
server:
  port: 8774
eureka:
  client:
    service-url:
      defaultZone:http://admin:123456@localhost:8761/eureka/
data:
  message:  '{cipher}b0664bb68c2f67bac420b3aee5403e06e6d88db081e408d16f13a6d32aa84cb1'
