spring:
    datasource:
      druid:
        url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: Test_12345
        stat-view-servlet:
            login-username:  admin
            login-password:  admin
mybatis:
  mapper-locations:  classpath:/mapper/*Mapper.xml
  configuration:
    #配置项：开启下划线到驼峰的自动转换，将数据库字段根据驼峰规则自动注入到对象属性
    map-underscore-to-camel-case:  true
