eureka:
    client:
        register-with-eureka: true
        fetch-registry: false
        service-url:
          defaultZone:  http://admin:123456@localhost:8761/eureka/
spring:
    zipkin:
        base-url:  http://localhost:9411
        sender:    
            type:  web
    sleuth:
        sampler:    
            probability:  1
            
