server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # 路由ID，没有固定规则但要求唯一，建议配合服务名
        - id: cloud-payment-provider
          # 匹配后提供服务的路由地址 (即目标服务地址)
          uri: http://localhost:8001
          # 断言会接收一个输入参数，返回一个布尔值结果
          predicates:
            # 路径相匹配的进行路由
            - Path=/payment/*
      discovery:
        locator:
          enabled: true
logging:
    level:
       org.springframework.cloud.gateway: trace
       org.springframework.http.server.reactive: debug
       org.springframework.web.reactive: debug
       reactor.ipc.netty:  debug
feign:
    hystrix:
      #开启熔断器
      enabled: true

